global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'matching-engine'
    static_configs:
      - targets: ['matching-engine:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'hft-gateway'
    static_configs:
      - targets: ['hft-gateway:8081']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka:9997']
    scrape_interval: 10s